### ISSUE TITLE
Fails to start on Windows 10 1709 (Fall Creators update)

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#1047]
Reported by a user:

> Frescobaldi: 2.19.0 -- Python: 2.7.1 -- python-ly: 0.9.4 -- Qt: 4.7.2 -- 
> PyQt: 4.8.4 -- sip: 4.12.2 -- poppler: unknown -- python-poppler-qt: 
> unknown -- OS: Windows-post2008Server-6.2.9200

> Version 3.0 won't start under my Windows 10 1709 (Fall Creators update).
> I've installed the Visual C++ 2008 runtime package before.
> The programm seems to start (HD-activity is visible, and the mouse cursor changes to busy), but after 2-3 seconds nothing more happens.

> Under my Windows 7 environment under Oracle VM Virtualbox this error-window appears:
> ![python_error_ver3_win7](https://user-images.githubusercontent.com/588454/33852126-96d29430-deb9-11e7-9aef-8d0f3741cd19.jpg)

**Comment by fedelibre** [comment]
> I've installed the Visual C++ 2008 runtime package before.

In the release notes it's written that required version is 2015:

> The Windows installer has been created and kindly contributed by Jörg Hoffmann.
> To run the Windows installer, it might be necessary to install the Visual Studio 2015 x86 redistributional Package.

I've successfully installed Frescobaldi 3.0.0 on Windows 7 with Visual C++2015.

**Comment by fedelibre** [comment]
@uliska @wbsoft I have the impression that this issue is already stale and it's going to be forgotten forever, as probably (I can't see the list of people subscribed to an issue?) the user who reported this problem never subscribed.

I would close this. If there's a real problem, other Windows users will let us know and hopefully offer some help to debug it.

**Comment by uliska** [comment]
I would say so too.
