### ISSUE TITLE
Text Highlighting Difficulties

### ISSUE THREAD

**Issue by Grendel-Grendel-Grendel** [wbsoft/frescobaldi#1068]
Just starting out with Frescobaldi on Manjaro Linux and finding that if I highlight text in the editor my cursor randomly "flies" away from what I'm highlighting towards the center of the text editor. This sometimes happens even if I just click on the editor. This makes using the program for anything larger than a single line almost impossible.

This only happens in Frescobaldi, and I was not accidentally touching my touchpad, so I doubt this is a hardware issue. Ordinary text being highlighted does this, but intermittently, while brackets being in the text ALWAYS causes the cursor to jump. Please let me know any more information that might be required and I will try to provide it ASAP.

**Comment by PeterBjuhr** [comment]
Thanks for the report! 
It might be helpful if you could provide a short moving screen, and also paste the version info from `Help -> About Frescobaldi`.

My first thought is that it's an issue between your OS and PyQt.

**Comment by uliska** [comment]
Does it make a difference if you're selecting (I assume that's what you mean) text with the mouse or the keyboard?

**Comment by yuy168** [comment]
@PeterBjuhr Here you go, the video came out really shitty for some reason but you can see the relevant behavior. In the first part, it continuously draws my mouse to the center of the editor whenever I try to select with the mouse. I followed @uliska 's suggestion and in the second half use the keyboard to successfully select text without errors.
https://my.mixtape.moe/gbdqiw.ogv

**Comment by PeterBjuhr** [comment]
Thanks for the recording!

Sorry, I should have said that you need to select the version tab aswell!

**Comment by yuy168** [comment]
@PeterBjuhr 

Frescobaldi: 3.0.0
Python: 3.6.5
python-ly: 0.9.5
Qt: 5.11.0
PyQt: 5.10.1
sip: 4.19.8
poppler: 0.64.0
python-poppler-qt: 0.24.1
OS: Linux-4.16.8-rt3-1-rt-x86_64-with-arch-Manjaro-Linux

**Comment by fedelibre** [comment]
I see that Manjaro is based on Arch.
Qt version is quite recent. On my Fedora system I have a slightly older version. Everything works fine.

> Frescobaldi: 3.0.0
> Python: 3.6.5
> python-ly: 0.9.5
> Qt: 5.10.1
> PyQt: 5.10
> sip: 4.19.7
> poppler: 0.61.1
> python-poppler-qt: 0.24.1
> OS: Linux-4.17.5-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight

**Comment by uliska** [comment]
I don't know if the (minor) version mismatch between Qt 5.11 and PyQt 5.10 is an issue, but it may well cause troubles. Qt is the basic infrastructure, written in C++, PyQt is the "binding" that makes all of Qt available to our Python code. AFAIK such bindings have to be "compiled against" the original, and so I can imagine that there may be slight conflicts when the bindings are older, i.e. may not have been compiled against the current version of Qt.

We had this problem for some time with python-poppler-qt which was not up-to-date agtains poppler and/or sip. (But this is not the problem here as python-poppler-qt is only relevant for the music viewer).

*If* that should be the problem I think we can't do anything about it from our side except hoping that the packages in Manjaro get in sync again (or maybe one can work around the issue by forcing specific versions in the package manager).

**Comment by uliska** [comment]
What is the state of this issue? Could it be reproduced, does @Grendel-Grendel-Grendel still have the problem or is still interested in it?

Without any secondary reproduction of the issue I'd tend to close it.

**Comment by uliska** [comment]
I will close this then. There's always the option of reopening.
