### ISSUE TITLE
Frescobaldi new git branch checkout not updated in title bar

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#1117]
If I switch to a new Frescobaldi branch (e.g. zoom-log-window), I can see the new active branch in the Git menu, while the branch in the title bar remains the old one (show-available-fonts):

![frescobaldi-switch-git-branch](https://user-images.githubusercontent.com/1644647/46721448-4eca8280-cc73-11e8-9487-28333f97f118.png)

**Comment by fedelibre** [comment]
I have the suspect that Git menu is wrong and the actual active branch is still the old one shown in the title. I realized it because the zoom-log-window branch started working as expected only after I closed and relaunched Frescobaldi.

I thought that Git menu allowed to switch branches without having to restart Frescobaldi.

@uliska What do you think?

**Comment by uliska** [comment]
All of the comments are sort-of correct ;-)

When the Git menu is populated it actually reads the info from Git, so it will show what Git considers the current branch.

However, the branch Frescobaldi is *running* from is the one that was active when it was launched, thus restarting will update the branch in the title bar as well.

Changing the branch "under" a running Instance of Frescobaldi won't make it *use* that branch.
However, doing so will bring it in a potentially fragile state: Frescobaldi will only load most modules upon use, which is deliberately done to make it start quickly. So if you call a function that loads a module, and if that module has been modified through a Git command after Frescobaldi has started it may well cause crashes or other unwanted behaviour.

Selecting an entry in the Git menu will

* (try to) checkout the branch (which may fail due to Git's safety net)
* open a dialog asking you if you want to restart Frescobaldi, and the do the restart for you.

So it's not possible to change the branch without restarting, but the Git menu saves you the effort of going into an external program, look up the available branches, do the checkout and manually restart Frescobaldi.

**Comment by fedelibre** [comment]
> Selecting an entry in the Git menu will
> 
>     * (try to) checkout the branch (which may fail due to Git's safety net)
> 
>     * open a dialog asking you if you want to restart Frescobaldi, and the do the restart for you.
> 
> 
> So it's not possible to change the branch without restarting, but the Git menu saves you the effort of going into an external program, look up the available branches, do the checkout and manually restart Frescobaldi.

Ok, now I understand.

I didn't realize it because I checked out the branch in a terminal while Frescobaldi was running and no dialog suggesting a restart appeared.
