### ISSUE TITLE
Outline: Crash when trying to show tooltip

### ISSUE THREAD

**Issue by nsprangers** [wbsoft/frescobaldi#1121]
**To reproduce:**

Open a file that has at least one variable. Select "Tools > Outline" to show the Outline dock. Hover over an entry in the outline and wait for a tooltip. A tooltip will not appear and the application crashes with the following info:

`Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/outline/widget.py", line 186, in event
    self.showToolTip(item)
  File "/usr/share/frescobaldi/frescobaldi_app/outline/widget.py", line 193, in showToolTip
    documenttooltip.show(self.cursorForItem(item))
  File "/usr/share/frescobaldi/frescobaldi_app/documenttooltip.py", line 88, in show
    widgets.customtooltip.show(label, pos)
NameError: name 'widgets' is not defined`

**System Information**
Debian Sid, 64-bit
Frescobaldi 3.0.0 from Debian repository

**Comment by uliska** [comment]
This has been fixed in https://github.com/wbsoft/frescobaldi/commit/67e8743156c7654bca080c2d218686d242869c77. Unfortunately, since then no new version has been released.

We have started planning a 3.1 release but I can't tell you anything about when that might happen (and when that will propagate to the Debian packages).

If you need this functionality you can either modify `/usr/share/frescobaldi/frescobaldi_app/documenttooltip.py`, line 88, changing `widgets.` to `gadgets.` (not really a recommendable approach), or run Frescobaldi from its Git repository (as described in the [Wiki](https://github.com/wbsoft/frescobaldi/wiki/Run-Frescobaldi-3-on-Linux). Since you already run Frescobaldi 3 from distro packages there should be no problems doing that.
