### ISSUE TITLE
[Flatpak] Improve interaction with files in directories Frescobaldi doesn't have access to

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1630]
Steps to reproduce:

- Install Frescobaldi from Flathub. Keep the default settings in Flatseal.
- Create a LilyPond file and save it in your home folder (not in a subdirectory).
- Compile the file.

While the file can be saved (presumably because the user explicitly requests the path in the GUI, so Flatpak authorizes it), there is no PDF at the end of the compilation in the home folder (because the app doesn't have permissions to write there).

While helping Ralph Palmer privately with his Frescobaldi issues, I saw that this was very confusing for him, as for most innocent users out there probably. Also, the top of the window has a path under /run like this:

![image](https://github.com/frescobaldi/frescobaldi/assets/37271310/081c71dd-b360-4c7f-b41d-a6520e4831c7)

which led him to search for the PDF file next to that location.

If we don't have permissions to write in the specified location (but how to detect it, as the failure seems silent for LilyPond?), we should probably display a message box explaining that the user should grant the permissions in Flatseal or save in a folder where we do have the permissions, like Documents.

(Note that I've created a "flatpak" label for issues that relate to Flatpak, but fit here better than on https://github.com/flathub/org.frescobaldi.Frescobaldi/issues because solving them requires code changes in Frescobaldi itself.)

**Comment by fedelibre** [comment]
I agree there are some issues to be solved to help users who do not know how Flatpak works.

BTW, I wonder if we may add a check and verify if Frescobaldi is running as flatpak or not (e.g. checking if frescobaldi path is `/app/bin`) and then display it in the Help>About Frescobaldi>Version:

> Frescobaldi: 3.3.0 (flatpak)

**Comment by fedelibre** [comment]
The LilyPond>Generated files menu is not working here. I'm on Fedora Workstation, but I'm pretty sure it works in Fedora Silverblue so I guess there's some missing package which should allow to find the PDF reader installed in the system.

![immagine](https://github.com/frescobaldi/frescobaldi/assets/1644647/544bc7d9-1733-488d-8079-ffb11c06935a)

**Comment by fedelibre** [comment]
I'm Ok with granting access to the home directory. PR is welcome :-)

I know that Flatpak purists will not agree with us, but I prefer making Frescobaldi users' life easier.

Just a side note. GNOME Software shows an Unsafe button for any application which does not comply with some security requirements. Frescobaldi currently is considered unsafe because it uses a legacy window system (X11) instead of Wayland. Granting access to the home directory will be another reason to get the Unsafe button, even if we eventually add Wayland support. We'll live with that :-)

Some explanatory screenshots:


![Schermata del 2023-09-23 17-23-42](https://github.com/frescobaldi/frescobaldi/assets/1644647/ce721349-2d36-4d3a-b621-77976a6de398)

![Schermata del 2023-09-23 17-18-46](https://github.com/frescobaldi/frescobaldi/assets/1644647/ef4cfd81-9444-431a-a120-d64ca5527a40)

![Schermata del 2023-09-23 17-23-07](https://github.com/frescobaldi/frescobaldi/assets/1644647/eeeb8235-6be5-4b75-8c4c-37350567d04e)
