### ISSUE TITLE
Porting to Qt5

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#359]
I'm working with a computer where for some reason Frescobaldi breaks by using Qt5 instead of Qt4. And I have not yet managed to change Qt version. While I'm finding a solution to the problem (I'm of course thankful for any advice!) I'm planning on taking the opportunity to learn more about the differences between Qt4 and Qt5. What I've read so far is that the porting should be fairly smooth. I've created a branch for changes in the code to adapt to Qt5: https://github.com/PeterBjuhr/frescobaldi/tree/Qt5.

**Comment by dliessi** [comment]
Qt5 does not support Mac OS X 10.6 (Snow Leopard) and it is (almost) impossible to build on 10.6.
Switching to Qt5 would drop Frescobaldi's support to Mac OS X <= 10.6, while with Qt4 it works correctly at least on Mac OS X >= 10.5 [1].

Looking for a way to support both Qt4 and Qt5 in Python I found [pyqode.qt](https://github.com/pyQode/pyqode.qt).
If I understand correctly, you can write code in PyQt5 style, importing modules from `pyqode.qt` instead of `PyQt5`: pyqode.qt will then use the first available Qt binding between PyQt5, PyQt4 and PySide (in this order of preference).

@wbsoft Do you think that we can try it?
We could port to PyQt5 in a dedicated branch, and once it is complete we could change `PyQt5` to `pyqode.qt` and test.

**Comment by wbsoft** [comment]
What is the Qt5 roadmap? Will it support Mac OS X in the future? We can wait. I am not in favor of an inbetween layer, although I did not yet read more about `pycode.qt`. Qt4 is good and a few issues (with upperplane characters) can be worked around.

**Comment by PaulMorris** [comment]
> On Jan 26, 2015, at 8:26 AM, Wilbert Berendsen <notifications@github.com> wrote:
> 
> What is the Qt5 roadmap? Will it support Mac OS X in the future? We can wait. 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/wbsoft/frescobaldi/issues/359#issuecomment-71459938>.
> 

Here’s some info:
http://doc.qt.io/qt-5.4/osx.html#os-x-versions <http://doc.qt.io/qt-5.4/osx.html#os-x-versions>

OS X 10.7 and 10.8 are fully supported.  It’s strange that there's no mention there of 10.9 or 10.10.  

(FWIW, according to wikipedia 10.6 was released in 2009 and is "Unsupported [by Apple] as of February 26, 2014, though the last security update happened in September 2013.”)
https://en.wikipedia.org/wiki/Mac_OS_X_Snow_Leopard <https://en.wikipedia.org/wiki/Mac_OS_X_Snow_Leopard>

**Comment by proski** [comment]
Eric IDE manages to support PyQt4 and PyQt5 (and also Python 2 and Python
3).
http://eric-ide.python-projects.org/

As I understand, all modules that need PyQt do "import
Toolbox.PyQt4ImportHook" and then the usual PyQt5 imports. If the imports
fail, they are replaced with the PyQt4 imports in the exception handler.

I believe PyQt5 support should not be on the agenda yet. Let's have a solid
Python 3 support in 2.18 first.

Pavel

**Comment by wbsoft** [comment]
> I believe PyQt5 support should not be on the agenda yet. Let's have a solid Python 3 support in 2.18 first.

Yes, I think that's good.

**Comment by dliessi** [comment]
Qt5 is fully supported in Mac OS X 10.8, 10.9 and 10.10, occasionally tested on 10.7 (where it is «known to run well»), unsupported in 10.6 (although Qt5 applications could be deployed to 10.6 with limited support) and before (where it doesn't work at all), see [Supported Platforms](http://doc.qt.io/qt-5/supported-platforms.html#reference-configurations) and [Qt for OS X](http://doc.qt.io/qt-5/osx.html).
I don't think this will change.

I must admit that I'm particularly interested in maintaining 10.6 support because my computer cannot run systems later than 10.6: dropping 10.6 support would mean that I couldn't contribute easily to the project and I couldn't even *use* Frescobaldi, although I would be able to build the Mac package (I have occasional access to OS X 10.10).
Of course Frescobaldi's development should not be blocked by my personal demands. :D

Anyway, I had a look at the pyqode.qt code, and as far as I can see it does exactly what they say: when you import a Qt module from `pyqode.qt` it tries to import it from PyQt5, if that fails it tries with PyQt4, and if that also fails it tries with PySide.
In a couple of modules it adds some definitions to PyQt4 for compatibility with PyQt5.

> 10.6 [...] is "Unsupported [by Apple]

Indeed.
But (my problems aside :D) Frescobaldi works perfectly on 10.6, so I think we should not drop support completely.

> As I understand, all modules that need PyQt do "import Toolbox.PyQt4ImportHook" and then the usual PyQt5 imports. If the imports fail, they are replaced with the PyQt4 imports in the exception handler.

That too seems a good solution.
Actually it is easier to use conditionally (see below).

> I am not in favor of an inbetween layer

As far as I can see in [Supported Platforms](http://doc.qt.io/qt-5/supported-platforms.html#reference-configurations), the switch to Qt5 would be a problem only on Mac OS X 10.6 (main Windows and Linux versions are either in the reference list or in the «occasionally tested» / «known to work well» list).
E.g. we could use pyqode.qt or the PyQt4ImportHook only on Mac OS X <= 10.6, e.g. by conditionally importing PyQt4ImportHook.

>> I believe PyQt5 support should not be on the agenda yet. Let's have a solid Python 3 support in 2.18 first.
>
> Yes, I think that's good.

I do agree.
I just wanted to point to a possible solution that would allow Frescobaldi's switch to Qt5 in the future without dropping Qt4 support.

**Comment by wbsoft** [comment]
Supporting both 4 and 5 is a nice idea, but aren't there other api differences between qt4 and 5?

**Comment by dliessi** [comment]
Yes, there are, but they are taken into account by pyqode.qt and PyQt4ImportHook (that I happen to like more).
See e.g. the function `load_module` in [PyQt4ImportHook](http://die-offenbachs.homelinux.org:48888/hg/eric/file/cdc77314be22/Toolbox/PyQt4ImportHook.py).

**Comment by dliessi** [comment]
The only problem is the license: Eric is GPL3+, Frescobaldi is GPL2+.
Copying code from Eric would require you to release Frescobaldi under GPL3(+) (i.e. it would require you *not* to release the code under GPL2).
We could also ask Detlev Offenbach to release PyQt4ImportHook as a separate Python module (with any license) or to release that single file as GPL2+.

**Comment by anthonyfok** [comment]
Now that Frescobaldi 2.18.x supports Python 3 perfectly (see #369), perhaps it is time to look into Porting to Qt5 again?  Especially because of this recent "development":

* Debian Bug#784610: [frescobaldi] Qt4's WebKit removal - https://bugs.debian.org/784610

**Comment by wbsoft** [comment]
Indeed we should port to Qt5 now.

**Comment by dliessi** [comment]
@wbsoft What do you think of [PyQt4ImportHook](http://die-offenbachs.homelinux.org:48888/hg/eric/file/c26e2a2dc0cb/Toolbox/PyQt4ImportHook.py)?
What do you think of the license issue?
(See previous comments.)

**Comment by anthonyfok** [comment]
@dliessi I am curious: Why do you prefer PyQt4ImportHook over pyqode.qt?

**Comment by dliessi** [comment]
@anthonyfok Well, PyQt4ImportHook seemed less intrusive and could be used conditionally only on platforms where Qt5 is problematic.
But thinking about this again after more than one year, the more general approach of pyqode.qt (and its taking care of the differences between Qt4 and Qt5) would probably be more future-proof.
Let's wait for @wbsoft's opinion.

**Comment by anthonyfok** [comment]
To satisfy my curiosity and to learn more about PyQt5, I have started using @wbsoft's earlier Qt5 porting effort ([py3-qt5 branch](https://github.com/wbsoft/frescobaldi/tree/py3-qt5) from February 2014) to port the current master branch to PyQt5.  I will be pushing my progress to the [qt5-2016 branch](https://github.com/anthonyfok/frescobaldi/tree/qt5-2016) at https://github.com/anthonyfok/frescobaldi/tree/qt5-2016.

**Comment by PeterBjuhr** [comment]
Great!

**Comment by jaddle** [comment]
FYI, debian is working on removing qt4 from its next release, so frescobaldi has already been removed from testing. A qt5 version would be most welcome asap!

**Comment by wbsoft** [comment]
Ok!

I prefer to just port everything over to plain Qt5, so not using a hook or glue layer.

Let's make a branch to port to Qt5. In my opinion it is good to require Python 3 then as well.

**Comment by dliessi** [comment]
> I prefer to just port everything over to plain Qt5, so not using a hook or glue layer.

Do you mean only during the transition or are you against using pyqode.qt also eventually?

A switch to pyqode.qt after the transition to Qt5 should be painless: as they say in the [docs](http://pythonhosted.org/pyqode.qt/)
> Basically, you write your code as if you were using PyQt5 but import qt from pyqode.qt instead of PyQt5.

**Comment by wbsoft** [comment]
Is there an advantage to use pycode.qt instead of PyQt5? If PyQt5 is available on all platforms I prefer to use that directly (optimizing the number of dependencies and decreasing the possible number of configurations/version combinations that could hide little bugs/corner cases).

**Comment by dliessi** [comment]
**If** Qt5 is available there is no advantage in using pyqode.qt (also almost no disadvantage, except for maybe a tiny bit of overhead in importing Qt modules, but it should be *very* little).
But my whole point is that Qt5 is **not** available on all platforms, notably on Mac OS 10.6, that happens to be my current OS.
Being responsible for Mac packaging of Frescobaldi, apart for my personal interest in keeping it alive on Mac OS 10.6, I wouldn't like to drop support on old Mac versions just because we don't want to use pyqode.qt (unless there are some serious drawbacks I am not seeing, of course).

See https://github.com/wbsoft/frescobaldi/issues/359#issuecomment-71654175 above for some more details.
If you want, have a look at [pyqode.qt](https://github.com/pyQode/pyqode.qt): it is very simple.

**Comment by proski** [comment]
I agree that we should keep a compatibility layer if practical. Dropping platforms used by developers may be very costly for the project, even if very few users need it. pyqode.qt uses an acceptable license and appears to be well maintained, so it looks like a good choice to me.

Likewise, if anybody needs Python 2 for development, objections for Python 2 support removal should be raised now.

**Comment by anthonyfok** [comment]
> To satisfy my curiosity and to learn more about PyQt5, I have started using @wbsoft's earlier Qt5 porting effort ([py3-qt5 branch](https://github.com/wbsoft/frescobaldi/tree/py3-qt5) from February 2014) to port the current master branch to PyQt5.  I will be pushing my progress to the [qt5-2016 branch](https://github.com/anthonyfok/frescobaldi/tree/qt5-2016) at https://github.com/anthonyfok/frescobaldi/tree/qt5-2016.

I have pushed the changes that I have made thus far to the aforementioned branch, mainly by rebasing @wbsoft's earlier effort onto the master, and fixing a few other issues.  Unfortunately, due to my inexperience in Python and Qt5 development, I have hit a snag which I don't think I can solve myself.  It seems to have to do with PyQt5's new support for *cooperative multi-inheritance* as described here:

> http://pyqt.sourceforge.net/Docs/PyQt5/multiinheritance.html

There is another minor issue that the splash screen does not show up with PyQt5 unless I added a short loop that does `app.qApp.processEvents()` and `sleep()` for a short period of time, say 0.1 seconds, though I am sure there is a better way of doing it.  (Not committed.)

So yes, all ye gurus and experts, please continue the Qt5 porting effort when you have time.  :-)  Many thanks!

**Comment by wbsoft** [comment]
I think I am able to solve the multiinheritance issue: the ViewHighlighter (viewhighlighter.py) is both a plugin object and a QObject (as it inherits widgets.arbitraryhighlighter which inherits QObject). I need to rewrite the init methods.

**Comment by wbsoft** [comment]
Dear friends, I want to port to Qt5 aqap :-) because of a few bugs with encoding and input methods (such as #429), and because Qt4 is disappearing... Qt5 brings some nice improvements.
I make a new qt5 branch and lets put there all the effort.

**Comment by wbsoft** [comment]
The new branch is qt5. It already works with some error message here and there. But I am already using it :)

There are too much little changes in PyQt5 that I propose to drop Qt4 support (and Py2 support), but require Qt5 and Python3 for Frescobaldi 3.

**Comment by dliessi** [comment]
> There are too much little changes in PyQt5 that I propose to drop Qt4 support (and Py2 support), but require Qt5 and Python3 for Frescobaldi 3.

@wilbert: I think I expressed my position clearly enough, and anyway a day will come eventually when Frescobaldi will drop support for Qt4, so I have no further objection.
In any case I'll be able to continue packaging Frescobaldi for Mac with Qt5 and Python3, using a more recent machine I can use rather regularly.

I will surely give a try to pyqode.qt on Frescobaldi, once ported to Qt5: I'll try to keep supporting older Macs as long as I can.
But I'll get back to this topic after some actual tests and comparisons with recent Macs.

**Comment by wbsoft** [comment]
@dliessi : I'm sorry, I over-read your comment that 10.6 has no Qt5 available. We should at least make sure that a good 2.18.x release is made and continue to be maintained for "older" platforms, also because 2.18 still supports python2.

**Comment by wbsoft** [comment]
Does everybody agree with dropping support for Python 2 and Qt4 and only support Python 3 and Qt5 for Frescobaldi 3.0?

**Comment by fedelibre** [comment]
@uliska Should we close this issue?
