### ISSUE TITLE
.pdf (publishing) stored in a strange place

### ISSUE THREAD

**Issue by oszmidt** [wbsoft/frescobaldi#609]
Hi, not sure if this is a bug- the .pdf file is not found in the same directory as the .ly file (where I would expect it) but in a Frescobaldi temp directory..
Can I change this behaviour?
I'am on a Macbook Pro 2011, Mac OS 10.8.5 using the precompiled version of Frescobaldi (Dmg)

thanks,  ole

**Comment by uliska** [comment]
Am 12.02.2015 um 00:47 schrieb oszmidt:
>
> Hi, not sure if this is a bug- the .pdf file is not found in the same 
> directory as the .ly file (where I would expect it) but in a 
> Frescobaldi temp directory..
> Can I change this behaviour?
> I'am on a Macbook Pro 2011, Mac OS 10.8.5 using the precompiled 
> version of Frescobaldi (Dmg)
>
> thanks, ole
>

This is not a bug but a matter of configuration.

There's an option in the "LilyPond Preferences" saying "Save document if 
possible".
You don't have that option checked, so Frescobaldi won't save your 
document before compiling (so you can have the illusion of an unsaved 
file). In order to achieve that Frescobaldi saves a copy of the modified 
document to a temp directory, and this directory is where the PDF will 
show up.

HTH
Urs

**Comment by oszmidt** [comment]
thanks a lot for that super quick answer!

**Comment by proski** [comment]
We should probably think of a better default behavior. Defaults that don't need explaining are better than those that do.

Suppose I have a program source, I open it in an IDE, add debug information and click the "Run" button. I want an executable to be created and run where it would be created without the IDE - under the same name, in the same directory. The benefit of the IDE is that I don't have to save my changes to the original file unless I'm happy with them. If the IDE or the whole OS crashes, I'd like to find my modification in a file in the same directory, not in the temporary directory that may not survive the reboot.

Should we treat music differently from code? Perhaps the only difference it that the output files could have different names from the "golden" version, as they are not "aware" of their names, i.e. they don't check argv or procfs and don't invoke software that might do it. On the other hand, it would be confusing if the output filename depended on whether the file was modified. The expectation is that running lilypond would overwrite the output, whether the source is saved or not.

In any case, using a temporary directory seems to be unhelpful.

**Comment by wbsoft** [comment]
I created the scratchdir function in particular for the case one wants to run LilyPond, but did not save the document yet (I.e. it has no filename). So I guess that once I make 'Save document if possible' the default, Frescobaldi simply saves when the document has been modified, and runs LilyPond, not in a temp dir.

As I considered saving the document without user consent intrusive (the user might simply try something), I made the option unchecked by default.

**Comment by proski** [comment]
Saving the document is definitely bad. I'm talking of the case when the document exists on the disk but has been modified. Instead of /tmp/frescobaldi-oF2kGo/tmpCMnvf0/test.ly it could be in the same directory as the original, but with a different name, perhaps with a number (predictable filenames should not be a security issue in the user's directory). I mean something like test#1.ly

**Comment by PeterBjuhr** [comment]
The default behavior has led to confusion before so I agree, perhaps an overall discussion is needed.

@proski if you mean that the file created in the same directory should be non-temporary, I think it would still be too intrusive as the user would end up with a lot of files. 

But I like the idea as an optional preference. It would give the user a backup file which could be helpful. I think then the previously saved version (test.ly) should be saved as test.bly or something and test.ly should be overwritten and compiled.

I think we should consider saving a temporary file but in the same directory (which is perhaps what you mean). Another possible solution would be to move the resulting pdf from the temp dir to the current dir overwriting any previous pdf. But that seems more awkward.

**Comment by wbsoft** [comment]
When a document already has a local filename, but is modified, (and the user has not enabled the "Save if possible" pref), we could save indeed the temporary document to the same directory. I don't think we need a number, as there will be only one temporary file written for a document, because that one will be overwritten every time. (and probably removed immediately as soon as the user saves the document).

We could make it a hidden file. E.g. when the doc has filename `music.ly`, we can call the "scratch" file `.tmp_music.ly`. But I don't think MS Windows will hide the file. Another possibility would be `music (tmp).ly`.

But a little issue is when we do use the temp file in the same directory, all PDF and other generated files with the temp filename prefix will also be created in the same folder and there is a big chance that all the temp.pdf and midi files etc. will remain there, even if the user saves the document and the temp file is not used anymore. Can we use the `-o` option of LilyPond to use the normal name as output prefix? (I.e. the doc is `music.ly`, we save `temp_music.ly`, run LilyPond with `-o music` so the generated file names are the same as when running LilyPond over the saved document itself. I did not yet test that.)

**Comment by wbsoft** [comment]
(Note that Frescobaldi always does make a backup when saving. If you enable the "Safety backup" option, the backup file is retained. The backup file is created by copying the old file to a new file with `~` suffix, and then write the document to the old file (without deleting it first).)

**Comment by PeterBjuhr** [comment]
Could the class `QTemporaryFile` http://pyqt.sourceforge.net/Docs/PyQt4/qtemporaryfile.html be used?

**Comment by PeterBjuhr** [comment]
>But a little issue is when we do use the temp file in the same directory, all PDF and other generated files with the temp filename prefix will also be created in the same folder and there is a big chance that all the temp.pdf and midi files etc. will remain there, even if the user saves the document and the temp file is not used anymore. Can we use the -o option of LilyPond to use the normal name as output prefix? (I.e. the doc is music.ly, we save temp_music.ly, run LilyPond with -o music so the generated file names are the same as when running LilyPond over the saved document itself. I did not yet test that.)

I've just tried this with the custom engrave. And it seems to work as expected.

**Comment by PeterBjuhr** [comment]
>(Note that Frescobaldi always does make a backup when saving. If you enable the "Safety backup" option, the backup file is retained. The backup file is created by copying the old file to a new file with ~ suffix, and then write the document to the old file (without deleting it first).)

Great! I didn't know that. I guess I haven't learned all the preferences yet.

**Comment by wbsoft** [comment]
> Could the class [QTemporaryFile] (http://pyqt.sourceforge.net/Docs/PyQt4/qtemporaryfile.html) be used?

I already use the Python equivalent `tempfile.mkdtemp`.

We could go with a special filename to avoid overwriting the real file, and the `-o` option to direct LilyPond to still use the normal filename for output. Note that an older generated PDF might be overwritten then, and that a user might not like that. I still think the tempdir solution is not bad, and maybe we should just inform the user better. With a non-intrusive popup for example.

**Comment by dliessi** [comment]
> Note that an older generated PDF might be overwritten then, and that a user might not like that.

I'm one of those users. I think that overwriting *any* user file should not be the default behaviour.
I also think that auto-saving a source file is less intrusive than overwriting a compiled file: you can undo the changes to the source in the editor, if you want (and some users will be using version control, anyway), but you cannot restore the previous PDF file.

> I still think the tempdir solution is not bad, and maybe we should just inform the user better.

+1

**Comment by PeterBjuhr** [comment]
>I still think the tempdir solution is not bad, and maybe we should just inform the user better. With a non-intrusive popup for example.

Do you mean that a message should pop up when the user tries to compile a document with unsaved changes? In such case I guess compilations by the auto engraving process has to be excluded.

**Comment by wbsoft** [comment]
Decided that we keep the scratchdir functioning like now, but that we 1) inform the user better (issue #614) and 2) maybe implement a way to recover documents that were lost on an app or os crash (issue #615). But that recover functionality probably will not depend on the scratchdir functionality, which is only used to have a place to run LilyPond.

**Comment by wbsoft** [comment]
Closing this bug because of above decision.
