### ISSUE TITLE
convert-ly adding linefeeds / carriage return

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#649]
I have just upgraded to the latest Lilypond, version 2.19.16. I'm using Frescobaldi 2.18 on Windows 8.1.

Running convert-ly on any of my Lilypond scores, I find that carriage returns and/or linefeeds get added to each line.

This:

```lilypond
\version "2.18.2"


\include "_paper_setup.ily"
\include "_slash_notation.ily"


% Define header and footer
\header {
 title = \markup \bold \larger "My Song"
 composer = \markup \large "Music by John Doe"
 poet = \markup \large "Lyrics by Jane Done"
 }
}
```

Becomes this:

```lilypond
\version "2.19.16"




\include "_paper_setup.ily"


\include "_slash_notation.ily"




% Define header and footer


\header {


 title = \markup \bold \larger "My Song"


 composer = \markup \large "Music by John Doe"


 poet = \markup \large "Lyrics by Jane Done"


 }


}
```
It turns out that the problem is with Frescobaldi. Running convert-ly from the command-line works fine, no carriage return and/or linefeed added.

**Comment by proski** [comment]
My guess it's because we are not using universal newlines anymore. Universal newlines make Popen return strings rather than bytes. The reason we don't want that behavior is because the strings still need to be decoded on Python 2, but not on Python 3. Without universal newlines, the behavior is uniform - we always decode bytes.

But all the above is just one aspect of universal newlines. The other one is, obviously, that the newlines are processed by some smart algorithm. We need to do it manually now.

**Comment by PeterBjuhr** [comment]
A fit for the 2.18.1 milestone?

**Comment by proski** [comment]
I'm afraid it's a regression, and then it's definitely 2.18.1 material.
