### ISSUE TITLE
Reviewing the menus

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#730]
Before the release of the manuscript viewer I think we should have (another) review of all the menus.

**Comment by PeterBjuhr** [comment]
I've started to think about the helpbutton. Is that consisent but the overall UI? I didn't find any another tool with a similar button.

**Comment by uliska** [comment]
The Layout Control Panel has a help button.
Yes, this isn't consistent yet, but I think the general direction should rather be to supply these buttons for the other tools too, one by one.

**Comment by uliska** [comment]
Added #731

**Comment by uliska** [comment]
This doesn't affect our release.

**Comment by uliska** [comment]
@PeterBjuhr Is there anything else you wanted to consider with this issue?

**Comment by uliska** [comment]
@PeterBjuhr as you didn't respond to my previous comment I consider this obsolete. Feel free to reopen if you think differently.

**Comment by PeterBjuhr** [comment]
@uliska Sorry for the lack of response. We'd other more important issues to discuss I guess.

**Comment by PeterBjuhr** [comment]
I'm sorry to reopen this again! But I'm having problems with the help-button. And the forced moved of the button to the right (in a recent test case) helped me express my concerns: It is good to have easy access to the help text if needed but it is presumably not a tool for every day use. Therefore I think the placement to the left is to much in the center of attention and a move to the right is preferable.

**Comment by uliska** [comment]
I agree.
But what I didn't manage on first try is moving it to the right end of
the toolbar. Neither addStretch nor an "empty" QWidget with
QSizePolicy.expanding seemed to work.

**Comment by PeterBjuhr** [comment]
You mean like a static position to the right and not just right-most in the toolbar? Perhaps that would be nice...

**Comment by PeterBjuhr** [comment]
Maybe you could add an own layout for this in such a case!?

**Comment by uliska** [comment]
Ah yes, probably one has to add an extra layer of layout manually. You add actions to a QToolBar directly and don't to its layout.
So what we need is `addStretch` to the `layout` that *contains* the toolbar and then add the help button to that layout too. But then we'd have to either

1. recreate the help button as a QToolButton (to add it to a layout using `addWidget`) or 
2. add a separate toolbar just for the help button

I think the second option is better because we also add the *action* to the context menu, and we might want to add something else to that right section someday later.

**Comment by uliska** [comment]
My assumptions have proven right :-)

Can it be closed now?

**Comment by PeterBjuhr** [comment]
Looks nice!

**Comment by PeterBjuhr** [comment]
One thing, the user should be able to hide also the help toolbar.

**Comment by uliska** [comment]
Oops, that's right. I'll fix that.
