### ISSUE TITLE
ManuscriptViewPanel.reload()?

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#745]
I've by now (33b37e5b) significantly cleaned up the `MansucriptViewPanel` class so it really only contains a small number of individual things while most can conveniently be done in the base class.

What I'm not sure about is the `reloadView()` method. You have overridden this @PeterBjuhr. Would you please have a second look if that separation of concerns is really correct, i.e. if the implementation of the base class is the generic one and the one in the subclass the specific one. And could there be some use for calling `super()` here to reuse more of the code? Of course this is asked with regard to a future integration of the musicview and other arbitrary viewers.

**Comment by uliska** [comment]
Edit: I don't want to suggest there's anything wrong with the current state, I just don't really see through it.

**Comment by PeterBjuhr** [comment]
I didn't really consider changing the implementation in the base class, but I think I made a comment about it in the commit message.

The two methods are in fact very different. I did the override because "reloadView" seemed as the proper name of what the method was doing and the parent method wasn't to be used at this point. 

Perhaps it could be considered to do a renaming to allow a different structure!
