### ISSUE TITLE
The GUI's zh_CN translation is not complete.

### ISSUE THREAD

**Issue by codeworm96** [wbsoft/frescobaldi#899]
Hi everyone,

I am a new user of frescobaldi. I found that some text in the GUI is not translated when language is set as zh_CN in frescobaldi.

As a native speaker of Chinese, I would like to provide some help in improving zh_CN translation, if needed.

**Comment by uliska** [comment]
Hi Zhang,

Am 04.03.2017 um 06:00 schrieb Zhang Yuning:
>
> Hi everyone,
>
> I am a new user of frescobaldi. I found that some text in the GUI is
> not translated when language is set as zh_CN in frescobaldi.
>

Most translations are not completely up-to-date, because this relies on
people like you to do the work. So thank you for getting in touch with us.

> As a native speaker of Chinese, I would like to provide some help in
> improving zh_CN translation, if needed.
>

Did you already read
https://github.com/wbsoft/frescobaldi/blob/master/README-translations?
Basically all you have to do is take the file
https://github.com/wbsoft/frescobaldi/blob/master/frescobaldi_app/po/zh_CN.po
and edit it to your liking.

If anything is still unclear don't hesitate to ask.

Best
Urs

**Comment by codeworm96** [comment]
Thank you for providing me those useful links. I am trying to improve the Chinese translation, but it will take some time.
