### ISSUE TITLE
Homebrew: No available formula with the name "frescobaldi" 

### ISSUE THREAD

**Issue by allenloves** [wbsoft/frescobaldi#913]
I tried to install Frescobaldi with homebrew, this is the error message I've got:

Error: No available formula with the name "frescobaldi" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

I did update and upgrade the homebrew before installation.  Is there anything missing?

**Comment by jefferyshivers** [comment]
Same - the formula(e) should be added, or Wiki updated to reflect that it can't be brew installed this time.

**Comment by dliessi** [comment]
Apparently the formula for Frescobaldi was [moved to the boneyard](https://github.com/Homebrew/homebrew-boneyard/blob/master/frescobaldi.rb).
You'll find some references to issues/pull requests there.

The Homebrew formula for Frescobaldi was originally created by @marnen and was not maintained by @wbsoft nor other stable members of the Frescobaldi team.
Please open an issue (or even better a pull request) at Homebrew.

I would prefer to wait and see if the formula can be updated and reinstated, before deleting the relevant parts from the wiki page.
In the meantime I added a notice at the top of the page. (@philmassart: could you please add it to the French version of the wiki page?)
Please reopen this issue when you'll have further information.

**Comment by dliessi** [comment]
Sorry, I missed this reference: #842

**Comment by marnen** [comment]
I moved the Frescobaldi formula to [my homebrew tap](https://github.com/marnen/homebrew-extras) years ago. The official repo hasn't had the latest version for quite a long time.

I also quit maintaining the Frescobaldi Homebrew formula because, now that it's a native Mac application, I no longer believe that providing a Homebrew formula for it is a good idea. What I _will_ do is provide a [Cask](https://caskroom.github.io/) formula.

**Comment by marnen** [comment]
Further, I'm kind of unhappy that the wiki page says that Fresco "cannot be installed using Homebrew", since the formula is still available in my tap, as described on that very wiki page (I edited it to reflect this fact).

Really, I'd like to remove the Homebrew installation instructions from the wiki altogether if people think that's OK. There is no reason to install Fresco through Homebrew today.

**Comment by marnen** [comment]
I edited the [wiki page](https://github.com/wbsoft/frescobaldi/wiki/How-to-install-Frescobaldi-on-Mac-OS-X) to indicate that it's better to use a prebuilt release on Mac OS if possible. @allenloves In other words, please don't bother with Homebrew for current Fresco. (If you think you need a Homebrew installation of Fresco despite this, please let me know your use case.)

**Comment by dliessi** [comment]
> I moved the Frescobaldi formula to my homebrew tap years ago. The official repo hasn't had the latest version for quite a long time.

This is not correct: the [formula that was moved to boneyard](https://github.com/Homebrew/homebrew-boneyard/blob/master/frescobaldi.rb) provides Frescobaldi 2.19.0, as [your formula](https://github.com/marnen/homebrew-extras/blob/master/frescobaldi.rb) does.

> Further, I'm kind of unhappy that the wiki page says that Fresco "cannot be installed using Homebrew", since the formula is still available in my tap, as described on that very wiki page (I edited it to reflect this fact).

Sorry about that, not being a Homebrew user I completely forgot about your tap.
Thanks for pointing out and fixing the wiki page.

**Comment by marnen** [comment]
@dliessi:
> the formula that was moved to boneyard provides Frescobaldi 2.19.0

Whoops! I haven't worked on this in ages, so my memory was apparently faulty. I thought there was at least one version that never made it into the official Homebrew repo.
