### ISSUE TITLE
Discuss Git repository object design

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#971]
One fundamental question we have to discuss is whether the current approach of instantiating one `vcs.gitrepo.Repo` object representing the whole repository is the right one. This design comes from the original task of handling Frescobaldi's app repository.

Probably we need some entity representing an individual file because we will want to handle the differences per document in the editor.

My initial idea is to keep the gitrepo.Repo object but add individual document files to a list within that Repo object as soon as a document is opened in the editor (means: we need an additional class representing an individual file).

(We have to take into account that multiple open documents may be part of different Git repositories (or even partly *not* in repositories)).

**Comment by wenxin-bupt** [comment]
I've written a simple git-job class. I'm testing git-job inside `view.py`.  

The git-job instance must have enough lifetime to get the output of the git executable file. We shouldn't create a git-job instance in each git-command function.  Since this instance will be destroyed at the end of the function's execution. 

Currently I just add a git-job instance into `view`'s attributes. It will have the same life time as a `view` instance. And based on this, I thought we should arrange one `gitrepo.Repo` instance to each `view` instance.   Because in previous discussion, a git-job instance is part of a `gitrepo.Repo` object. That's my thought. 

One `gitrepo.Repo` object to handle all the files is good.  I prefer your idea. It may affect less code outside the vcs module.

**Comment by uliska** [comment]
> We shouldn't create a git-job instance in each git-command function. Since this instance will be destroyed at the end of the function's execution.

This is not completely true. Depending on the owner you pass the QProcess constructor it may last as long as the application. But I agree that we will need exactly one job instance per document tab.

But there's one thing that should be different: We may need multiple `Repo` instances in the view, so there must be a list or dictionary:

a) documents may come from different repositories, so they should be handled by separate `Repo` instances. This may not be absolutely necessary, but I think it's better to have this separate. For example the `Repo` instance stores the repository root.

b) documents may (in the future) even come from repositories of different VCS like e.g. Mercurial.

So I suggest:

* Create a "repositories" object as a member of the View instance
* Whenever a document is opened
    * check if it is version controlled (and which VCS)
    * if it is version controlled check if the repository is already added to the "repositories" list
    * if not then greate a `<vcstype>.Repo` instance and add the document to the list of watched files

I think it is important to keep an eye on the last item: we want to be able to load a `Repo` instance that matches the type of VCS the repository is in (even when we're only dealing with Git so far). Then we have a `Repo` object and all these objects must have the same interface. This also means: when you want to add "public" functionality to gitrepo.Repo you should always add it as an abstract method to abstractrepo.Repo and override it in gitrepo.Repo.

**Comment by uliska** [comment]
This discussion has been superseded by the discussion in #974.

We create *one* `Repo` object as a member of `View` (my initial description was wrong: the "View" is actually one editor with one document and not the whole widget with all the tabs).
